// frontend/src/pages/Landing.jsx

import React from 'react';
import { Link } from 'react-router-dom';
import { Zap, Brain, FileText, TrendingUp, Shield, BookOpen, ChevronRight, CheckCircle } from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'IBM Granite AI',
    desc: 'Powered by IBM Granite via watsonx.ai — enterprise-grade AI generating real, actionable insights.',
  },
  {
    icon: FileText,
    title: 'Complete Blueprint',
    desc: '13 comprehensive sections: problem, solution, BMC, market analysis, competitors, GTM strategy, and more.',
  },
  {
    icon: TrendingUp,
    title: 'Market & Competitor Analysis',
    desc: 'In-depth market sizing, trend analysis, and competitive landscape specific to your startup idea.',
  },
  {
    icon: BookOpen,
    title: 'RAG-Powered Research',
    desc: 'Retrieval-augmented generation surfaces real government schemes, funding sources, and legal requirements.',
  },
  {
    icon: Shield,
    title: 'Business Model Canvas',
    desc: 'Visual 9-block BMC with AI-generated content, regeneratable block by block.',
  },
  {
    icon: Zap,
    title: 'PDF Export',
    desc: 'Download a professional PDF blueprint ready to present to investors, mentors, or evaluators.',
  },
];

const steps = [
  { num: '01', title: 'Enter Your Idea', desc: 'Describe your startup idea, industry, target market, and stage.' },
  { num: '02', title: 'AI Analysis', desc: 'Our 12-module agent analyzes every dimension of your startup.' },
  { num: '03', title: 'Review Blueprint', desc: 'Explore all sections with tabbed navigation and visual BMC.' },
  { num: '04', title: 'Export & Share', desc: 'Download a professional PDF ready for stakeholders.' },
];

export default function Landing() {
  return (
    <div className="min-h-screen bg-white">
      {/* Navbar */}
      <nav className="border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="bg-blue-600 p-1.5 rounded-lg">
              <Zap className="h-5 w-5 text-white" />
            </div>
            <span className="font-bold text-xl">Blueprint<span className="text-blue-600">AI</span></span>
          </div>
          <div className="flex items-center gap-4">
            <Link to="/login" className="text-sm text-gray-600 hover:text-gray-900">Login</Link>
            <Link to="/signup" className="text-sm bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-medium transition-colors">
              Get Started Free
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="max-w-7xl mx-auto px-6 py-20 text-center">
        <div className="inline-flex items-center gap-2 bg-blue-50 text-blue-700 px-4 py-1.5 rounded-full text-sm font-medium mb-6">
          <Zap className="h-3.5 w-3.5" />
          AICTE Problem Statement 20 · Powered by IBM Granite
        </div>
        <h1 className="text-5xl font-extrabold text-gray-900 leading-tight mb-6">
          Turn Your Startup Idea<br />into a Complete Blueprint
        </h1>
        <p className="text-xl text-gray-500 max-w-2xl mx-auto mb-10">
          AI-powered analysis using IBM Granite generates a professional startup blueprint with market research,
          competitor analysis, Business Model Canvas, government schemes, and funding opportunities.
        </p>
        <div className="flex items-center justify-center gap-4">
          <Link
            to="/signup"
            className="inline-flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-8 py-3.5 rounded-xl font-semibold text-lg transition-colors"
          >
            Generate Your Blueprint
            <ChevronRight className="h-5 w-5" />
          </Link>
          <Link to="/login" className="text-gray-600 hover:text-gray-900 font-medium">
            Already have an account →
          </Link>
        </div>

        {/* Trust indicators */}
        <div className="mt-12 flex items-center justify-center gap-8 text-sm text-gray-400">
          {['IBM Granite LLM', 'RAG Architecture', 'DPIIT Schemes', 'PDF Export', 'Secure & Private'].map((item) => (
            <div key={item} className="flex items-center gap-1.5">
              <CheckCircle className="h-4 w-4 text-green-500" />
              {item}
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="bg-gray-50 py-20">
        <div className="max-w-7xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-center text-gray-900 mb-3">Everything You Need</h2>
          <p className="text-center text-gray-500 mb-12">13 comprehensive sections generated by AI and grounded in real data</p>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((f) => (
              <div key={f.title} className="bg-white rounded-xl p-6 border border-gray-200 hover:border-blue-200 hover:shadow-md transition-all">
                <div className="bg-blue-50 w-10 h-10 rounded-lg flex items-center justify-center mb-4">
                  <f.icon className="h-5 w-5 text-blue-600" />
                </div>
                <h3 className="font-semibold text-gray-900 mb-2">{f.title}</h3>
                <p className="text-sm text-gray-500 leading-relaxed">{f.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-20 max-w-7xl mx-auto px-6">
        <h2 className="text-3xl font-bold text-center text-gray-900 mb-3">How It Works</h2>
        <p className="text-center text-gray-500 mb-12">From idea to full blueprint in minutes</p>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {steps.map((step, i) => (
            <div key={step.num} className="text-center">
              <div className="text-4xl font-extrabold text-blue-100 mb-3">{step.num}</div>
              <h3 className="font-semibold text-gray-900 mb-2">{step.title}</h3>
              <p className="text-sm text-gray-500">{step.desc}</p>
              {i < steps.length - 1 && (
                <div className="hidden md:block absolute mt-6 ml-full">
                  <ChevronRight className="h-6 w-6 text-gray-300" />
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="bg-blue-600 py-16 text-center">
        <div className="max-w-2xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-white mb-4">Ready to Build Your Startup?</h2>
          <p className="text-blue-100 mb-8">Join and generate your first AI-powered startup blueprint for free.</p>
          <Link
            to="/signup"
            className="inline-flex items-center gap-2 bg-white text-blue-600 hover:bg-blue-50 px-8 py-3.5 rounded-xl font-semibold text-lg transition-colors"
          >
            Get Started Free
            <ChevronRight className="h-5 w-5" />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-100 py-8 text-center text-sm text-gray-400">
        <p>Startup Blueprint Generator · AICTE Problem Statement 20 · Built with IBM Granite & watsonx.ai</p>
      </footer>
    </div>
  );
}
