// frontend/src/utils/pdfExport.js
// Professional PDF export using jsPDF + jsPDF-AutoTable

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

const COLORS = {
  primary: [37, 99, 235],       // blue-600
  dark: [17, 24, 39],           // gray-900
  medium: [75, 85, 99],         // gray-600
  light: [156, 163, 175],       // gray-400
  bg: [249, 250, 251],          // gray-50
  white: [255, 255, 255],
  accent: [16, 185, 129],       // green-500
};

function addHeader(doc, title, subtitle, pageWidth) {
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...COLORS.white);
  doc.text(title, 14, 13);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(190, 210, 255);
  doc.text(subtitle, 14, 22);

  doc.setTextColor(...COLORS.dark);
}

function addSectionTitle(doc, text, y) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.primary);
  doc.text(text, 14, y);
  doc.setDrawColor(...COLORS.primary);
  doc.setLineWidth(0.5);
  doc.line(14, y + 2, 196, y + 2);
  doc.setTextColor(...COLORS.dark);
  return y + 8;
}

function addBodyText(doc, text, x, y, maxWidth = 180, fontSize = 9) {
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(fontSize);
  doc.setTextColor(...COLORS.medium);
  const lines = doc.splitTextToSize(String(text || ''), maxWidth);
  doc.text(lines, x, y);
  return y + lines.length * (fontSize * 0.45) + 2;
}

function addBulletList(doc, items, x, y, maxWidth = 170) {
  if (!items || items.length === 0) return y;
  items.forEach((item) => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.medium);
    doc.text('•', x, y);
    const lines = doc.splitTextToSize(String(item), maxWidth - 5);
    doc.text(lines, x + 5, y);
    y += lines.length * 4 + 1;
  });
  return y;
}

function checkPageBreak(doc, y, margin = 20) {
  if (y > doc.internal.pageSize.height - margin) {
    doc.addPage();
    return 35;
  }
  return y;
}

function addInfoBox(doc, label, value, x, y, width = 86) {
  doc.setFillColor(...COLORS.bg);
  doc.roundedRect(x, y, width, 16, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.light);
  doc.text(label.toUpperCase(), x + 3, y + 5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.dark);
  const lines = doc.splitTextToSize(String(value || '-'), width - 6);
  doc.text(lines[0], x + 3, y + 12);
  return y + 20;
}

// ─────────────────────────────────────────────────────
export async function exportToPDF(blueprint) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = doc.internal.pageSize.width;
  const idea = blueprint.startupIdea;
  const sections = blueprint.sections || {};

  // ── Cover page ──────────────────────────────────────
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 90, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(...COLORS.white);
  doc.text(idea?.startupName || 'Startup', 14, 35);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(190, 210, 255);
  doc.text('Startup Blueprint', 14, 45);

  doc.setFontSize(9);
  doc.setTextColor(190, 210, 255);
  doc.text(`Generated by IBM Granite AI · ${new Date().toLocaleDateString()}`, 14, 55);

  doc.setFillColor(...COLORS.white);
  doc.roundedRect(14, 65, pageWidth - 28, 20, 3, 3, 'F');
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.medium);
  const pitch = sections.executive_summary?.content?.elevatorPitch || '';
  const pitchLines = doc.splitTextToSize(`"${pitch}"`, pageWidth - 36);
  doc.text(pitchLines, 18, 74);

  // Idea details
  let y = 105;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.dark);
  doc.text('Startup Details', 14, y);
  y += 6;

  const details = [
    ['Industry', idea?.industry], ['Stage', idea?.stage],
    ['Location', idea?.targetLocation], ['Team Size', `${idea?.teamSize} people`],
    ['Budget', idea?.initialBudget], ['Target Customer', idea?.targetCustomer],
  ];
  let col = 0;
  details.forEach(([label, value]) => {
    const xPos = col === 0 ? 14 : 110;
    addInfoBox(doc, label, value, xPos, y, 86);
    if (col === 1) y += 22;
    col = col === 0 ? 1 : 0;
  });
  y += 22;

  // ── Page 2: Executive Summary ────────────────────────
  doc.addPage();
  addHeader(doc, idea?.startupName, 'Executive Summary', pageWidth);
  y = 38;

  const summary = sections.executive_summary?.content;
  if (summary) {
    y = addSectionTitle(doc, 'Executive Summary', y);
    y = addBodyText(doc, summary.executiveSummary, 14, y, 182, 9);
    y += 4;

    y = checkPageBreak(doc, y);
    y = addSectionTitle(doc, 'Mission & Vision', y);
    addInfoBox(doc, 'Mission', summary.missionStatement, 14, y, 86);
    addInfoBox(doc, 'Vision', summary.visionStatement, 110, y, 86);
    y += 22;
  }

  // ── Problem & Solution ───────────────────────────────
  y = checkPageBreak(doc, y, 40);
  y = addSectionTitle(doc, 'Problem & Solution', y);

  const prob = sections.problem?.content;
  if (prob) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.dark);
    doc.text('Problem', 14, y);
    y += 5;
    y = addBodyText(doc, prob.problem?.mainProblem, 14, y);
    y = addBodyText(doc, `Who experiences it: ${prob.problem?.whoExperiences}`, 14, y);
    y += 3;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Solution', 14, y);
    y += 5;
    y = addBodyText(doc, prob.solution?.proposedSolution, 14, y);
    y += 3;

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Value Proposition', 14, y);
    y += 5;
    y = addBodyText(doc, prob.usp?.valueProposition, 14, y);
    y = addBulletList(doc, prob.usp?.uniqueSellingPropositions, 14, y);
  }

  // ── Market Analysis ──────────────────────────────────
  doc.addPage();
  addHeader(doc, idea?.startupName, 'Market Analysis', pageWidth);
  y = 38;

  const market = sections.market?.content;
  if (market) {
    y = addSectionTitle(doc, 'Market Overview', y);
    y = addBodyText(doc, market.marketOverview, 14, y);
    y += 4;

    y = checkPageBreak(doc, y);
    y = addSectionTitle(doc, 'Market Size', y);
    ['tam', 'sam', 'som'].forEach((key, i) => {
      const xPos = 14 + i * 62;
      doc.setFillColor(...COLORS.bg);
      doc.roundedRect(xPos, y, 58, 22, 2, 2, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.primary);
      doc.text(key.toUpperCase(), xPos + 3, y + 7);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7);
      doc.setTextColor(...COLORS.dark);
      const val = doc.splitTextToSize(market.marketSize?.[key]?.value || '-', 50);
      doc.text(val[0], xPos + 3, y + 14);
    });
    y += 28;

    if (market.keyTrends?.length > 0) {
      y = checkPageBreak(doc, y);
      y = addSectionTitle(doc, 'Key Trends', y);
      autoTable(doc, {
        startY: y,
        head: [['Trend', 'Impact', 'Relevance']],
        body: market.keyTrends.map((t) => [t.trend, t.description, t.relevance]),
        styles: { fontSize: 8 },
        headStyles: { fillColor: COLORS.primary },
        margin: { left: 14, right: 14 },
      });
      y = doc.lastAutoTable.finalY + 6;
    }
  }

  // ── Competitor Analysis ──────────────────────────────
  y = checkPageBreak(doc, y, 40);
  const competitors = sections.competitors?.content;
  if (competitors?.directCompetitors?.length > 0) {
    y = addSectionTitle(doc, 'Competitor Analysis', y);
    autoTable(doc, {
      startY: y,
      head: [['Competitor', 'Description', 'Strengths', 'Weaknesses']],
      body: competitors.directCompetitors.map((c) => [
        c.name,
        c.description,
        c.strengths?.join(', ') || '',
        c.weaknesses?.join(', ') || '',
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: COLORS.primary },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 35 }, 1: { cellWidth: 45 } },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  // ── Business Model Canvas ────────────────────────────
  doc.addPage();
  addHeader(doc, idea?.startupName, 'Business Model Canvas', pageWidth);
  y = 38;

  const bmc = sections.bmc?.content;
  if (bmc) {
    const blocks = [
      ['Key Partners', bmc.keyPartners?.items],
      ['Key Activities', bmc.keyActivities?.items],
      ['Value Propositions', bmc.valuePropositions?.items],
      ['Customer Relationships', bmc.customerRelationships?.items],
      ['Customer Segments', bmc.customerSegments?.items],
      ['Key Resources', bmc.keyResources?.items],
      ['Channels', bmc.channels?.items],
      ['Cost Structure', bmc.costStructure?.items],
      ['Revenue Streams', bmc.revenueStreams?.items],
    ];

    autoTable(doc, {
      startY: y,
      head: [['Block', 'Content']],
      body: blocks.map(([name, items]) => [name, (items || []).join('\n• ')]),
      styles: { fontSize: 8, cellPadding: 3 },
      headStyles: { fillColor: COLORS.primary },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 50 } },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  // ── Revenue & Budget ─────────────────────────────────
  doc.addPage();
  addHeader(doc, idea?.startupName, 'Revenue Model & Budget', pageWidth);
  y = 38;

  const revenue = sections.revenue?.content;
  if (revenue?.recommendedModels?.length > 0) {
    y = addSectionTitle(doc, 'Revenue Models', y);
    autoTable(doc, {
      startY: y,
      head: [['Model', 'Description', 'Priority']],
      body: revenue.recommendedModels.map((m) => [m.model, m.description, m.priority]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: COLORS.primary },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  const budget = sections.budget?.content;
  if (budget?.breakdown?.length > 0) {
    y = checkPageBreak(doc, y, 40);
    y = addSectionTitle(doc, `Budget — ${budget.totalEstimatedBudget}`, y);
    autoTable(doc, {
      startY: y,
      head: [['Category', 'Estimated Amount', '%']],
      body: budget.breakdown.map((b) => [b.category, b.estimatedAmount, `${b.percentage}%`]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: COLORS.primary },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 6;
    y = addBodyText(doc, `⚠ ${budget.disclaimer}`, 14, y, 182, 8);
  }

  // ── GTM Strategy ─────────────────────────────────────
  doc.addPage();
  addHeader(doc, idea?.startupName, 'Go-To-Market Strategy', pageWidth);
  y = 38;

  const gtm = sections.gtm?.content;
  if (gtm) {
    y = addSectionTitle(doc, 'GTM Overview', y);
    y = addBodyText(doc, gtm.gtmOverview, 14, y);
    y += 4;

    if (gtm.actionPlan) {
      y = checkPageBreak(doc, y);
      y = addSectionTitle(doc, '30 / 60 / 90 Day Plan', y);
      const planRows = [];
      if (gtm.actionPlan.days1to30) planRows.push(['Days 1–30', gtm.actionPlan.days1to30.theme, gtm.actionPlan.days1to30.actions?.join('\n') || '']);
      if (gtm.actionPlan.days31to60) planRows.push(['Days 31–60', gtm.actionPlan.days31to60.theme, gtm.actionPlan.days31to60.actions?.join('\n') || '']);
      if (gtm.actionPlan.days61to90) planRows.push(['Days 61–90', gtm.actionPlan.days61to90.theme, gtm.actionPlan.days61to90.actions?.join('\n') || '']);

      autoTable(doc, {
        startY: y,
        head: [['Period', 'Theme', 'Actions']],
        body: planRows,
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: { fillColor: COLORS.primary },
        margin: { left: 14, right: 14 },
      });
      y = doc.lastAutoTable.finalY + 6;
    }
  }

  // ── Government Schemes ───────────────────────────────
  doc.addPage();
  addHeader(doc, idea?.startupName, 'Government Schemes & Funding', pageWidth);
  y = 38;

  const schemes = sections.schemes?.content;
  if (schemes?.schemes?.length > 0) {
    y = addSectionTitle(doc, 'Government Schemes', y);
    autoTable(doc, {
      startY: y,
      head: [['Scheme', 'Organisation', 'Eligibility', 'Benefits']],
      body: schemes.schemes.map((s) => [
        s.name, s.organisation || '', s.eligibility || '', s.benefits?.join(', ') || '',
      ]),
      styles: { fontSize: 7.5 },
      headStyles: { fillColor: COLORS.primary },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 6;
    y = addBodyText(doc, `⚠ ${schemes.disclaimer}`, 14, y, 182, 8);
  }

  const funding = sections.funding?.content;
  if (funding?.fundingOpportunities?.length > 0) {
    y = checkPageBreak(doc, y, 40);
    y = addSectionTitle(doc, 'Funding Opportunities', y);
    autoTable(doc, {
      startY: y,
      head: [['Source', 'Type', 'Stage', 'Funding Range']],
      body: funding.fundingOpportunities.map((f) => [
        f.source, f.type || '', f.stage || '', f.fundingRange || 'Varies',
      ]),
      styles: { fontSize: 8 },
      headStyles: { fillColor: COLORS.primary },
      margin: { left: 14, right: 14 },
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  // ── Legal ────────────────────────────────────────────
  const legal = sections.legal?.content;
  if (legal) {
    y = checkPageBreak(doc, y, 40);
    y = addSectionTitle(doc, 'Legal Considerations', y);
    if (legal.businessRegistration) {
      y = addBodyText(doc, `Recommended Structure: ${legal.businessRegistration.recommendedStructure}`, 14, y);
      y = addBodyText(doc, legal.businessRegistration.rationale, 14, y);
      y += 3;
    }
    y = addBodyText(doc, `⚠ ${legal.disclaimer}`, 14, y, 182, 8);
  }

  // ── Footer on all pages ──────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const ph = doc.internal.pageSize.height;
    doc.setDrawColor(...COLORS.light);
    doc.setLineWidth(0.3);
    doc.line(14, ph - 12, pageWidth - 14, ph - 12);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.light);
    doc.text(`${idea?.startupName} — Startup Blueprint · Generated by IBM Granite AI · BlueprintAI`, 14, ph - 7);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - 20, ph - 7);
  }

  // ── Save ─────────────────────────────────────────────
  const filename = `${(idea?.startupName || 'blueprint').replace(/\s+/g, '-').toLowerCase()}-blueprint.pdf`;
  doc.save(filename);
}
